// <auto-generated />
namespace Task_1_with_Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCart));
        
        string IMigrationMetadata.Id
        {
            get { return "202007141154454_addCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
